### PR TITLE
Stats modifier + documentation and tests for datanode

### PR DESCRIPTION
**Pull request by emilydolson**
Adds the stats modifier (tracking variance, standard deviation, skew, and kurtosis) to the DataNode class. Also adds documentation and tests to the entire source/data directory. 

Additionally, this pull request fixes a compile error that would occur if you tried to build a DataInterface to a DataNode without the range modifier. The error was caused by the fact that the node wouldn't have methods like `GetTotal()`, `GetMean()`, etc. I fixed it by adding placeholder versions of these methods to the base DataNode class. All of them throw an emp_assert in debug mode and return 0. Is that the appropriate way of handling this? I based it off of the handling of `SetName()` etc. But I could imagine that you wouldn't actually want something as strong as an assert (maybe this is another place where emp_warning would be nice). Conversely, you could make the argument that returning any value is dangerous, because it could potentially go undetected.

### CODE REVIEW

**Comment by mercere99** [comment]
These look good.  One (minor) point is that for short Doxygen comments we've been using /// throughout the rest of the code rather than /** and */.

**Comment by mercere99** [comment]
FYI, I'm unifying the commenting in the files and fixing the comments to reflect your questions.

**Comment by mercere99** [comment]
// @ELD: This seems a little confusing - it's not obvious which modifiers can track resets.

Any DataNode that tracks history will know how many resets there have been and will override this function.

**Comment by mercere99** [comment]
Nope - the Histogram problem isn't something that I was aware of!  I did note that they whole system could be made simpler.

**Comment by emilydolson** [comment]
That sounds good for the ResetCount thing.

For histogram, this is the test I wrote. It fails because the bin width doesn't actually get changed from 10 to 2. When I do that manually, (by adding `bins.Adjust(emp::vector<double>(num_bins, width));` to the `SetupBins()` method) it puts the 19 in the 6th bin instead of the 9th. Which makes it seem like the problem is somewhere in IndexMap, which is not a part of the code I'm super familiar with.

`TEST_CASE("Test histogram", "[data]") {
    emp::DataNode<double, emp::data::Current, emp::data::Range, emp::data::Histogram, emp::data::Pull, emp::data::Log> data;
    data.SetupBins(1,21,10);
    data.Add(1,2,1,19);

    REQUIRE(data.GetHistMin() == 1);
    REQUIRE(data.GetHistWidth(5) == 2);

    REQUIRE(data.GetBinMins() == emp::vector<double>({1,3,5,7,9,11,13,15,17,19}));

    std::cout << emp::to_string(data.GetBinMins()) << std::endl;
    std::cout << emp::to_string(data.GetHistCounts()) << std::endl;
    REQUIRE(data.GetHistCount(9) == 1);
    REQUIRE(data.GetHistCounts() == emp::vector<size_t>({3,0,0,0,0,0,0,0,0,1}));

    data.Reset();
    REQUIRE(data.GetHistCounts() == emp::vector<size_t>({0,0,0,0,0,0,0,0,0,0}));    
}`

**Pull request merged**
