### PR TITLE
Othello game implementation

### PR DESCRIPTION
**Pull request by amlalejini**
Includes:
- Othello class
- Othello example
- Othello tests
- two old, minor EventDrivenGP modifications

### CODE REVIEW

**Comment by amlalejini** [comment]
Just added < operator overloads to SignalGP (EventDrivenGP.h), and modified AvidaGP::Instruction struct's < operator overload to also compare arguments in addition to instruction IDs.

**Comment by mercere99** [comment]
I'm not sure I understand why N(), S(), etc... are constexpr functions that return a value, as opposed to just being a value...

`static inline constexpr size_t N() { return DIRECTION_ID__N; }`

**Comment by amlalejini** [comment]
You know, I don't now either, outside of: it was more satisfying to type N() than NORTH or whatever. I'm in no way attached to it.

**Comment by mercere99** [comment]
Okay -- I don't have a problem with the functions, and we can streamline it later.

Not sure why its still saying "Review Required".  I'll see if resolving conflicts helps.

**Pull request merged**
