### PR TITLE
Add << interface for DataFile

### PR DESCRIPTION
**Pull request by mmore500**
This change allows the user to write directly to the DataFile.

### CODE REVIEW

**Comment by mmore500** [comment]
I've been wanting to have a DataFile iterate (through unique genotypes, through all positions on a grid) every time that Update is called, printing multiple lines for each time Update (one for each unique genotoype, one for each position on a grid). Using the commit above, I've hacked together two ways of doing this. I feel like there should be a nice way to accomplish this in the DataFile class (or another class) but I'm not sure what the design should look like... although probably not like these approaches.

**Comment by mmore500** [comment]
```
  /*
   * Setup our data file to collect a genotypic census.
   */
  emp::DataFile& SetupCensusFile(const std::string& filename) {

    Organism& examp = emp::World<Organism>::GetOrg(0);

    auto& file = emp::World<Organism>::SetupFile(filename);

    file.SetupLine("","","");
    // print header
    file << "seed";
    file << ",";
    file << "update";
    file << ",";
    examp.PrintHeader(file);
    file << ",";
    file << "count";
    file << "\n";

    // this print function gets called intermittently
    file.Add(
      [this](std::ostream& os){
        std::map<Organism,size_t> org_counts;
        for (emp::Ptr<Organism> org : emp::World<Organism>::pop) {
           if (org) org_counts[*org] = 0;  // Initialize needed entries
        }
        for (emp::Ptr<Organism> org : emp::World<Organism>::pop) {
          if (org) org_counts[*org] += 1; // Count actual types.
        }
        for (auto x : org_counts) {
          os << SEED << ",";
          os << emp::World<Organism>::GetUpdate() << ",";
          x.first.Print(os);
          os << ",";
          os << x.second << std::endl;
        }

      },"","");

    return file;
  }

  /*
   * Setup our data file to collect intermittent channel maps.
   */
  emp::DataFile& SetupChannelMapFile(
    const std::string& filename,
    DishtinyConfig& dconfig
  ) {

    auto& file = emp::World<Organism>::SetupFile(filename);
    // we will write our own timing function and register it with OnUpdate
    file.SetTiming([this](size_t update){ return false; });

    const size_t cdata_freq = dconfig.CDATA_FREQ();

    file.AddVar(SEED, "seed", "Random generator seed");

    file.AddVar(emp::World<Organism>::update, "update" , "Update");

    file.AddFun<int>([this](){
      return spec.GetX(channel_map_iterator);
    },"ch_x","TODO");

    file.AddFun<int>([this](){
      return spec.GetY(channel_map_iterator);
    },"ch_y","TODO");

    for (size_t lev = 0; lev < NLEV; ++lev) {
      file.AddFun<int>([this, lev](){
        return channel.GetChannel(lev, channel_map_iterator);
      },"channel"+std::to_string(lev),"TODO");
    }

    file.PrintHeaderKeys();

    emp::World<Organism>::OnUpdate([this, cdata_freq, &file](size_t update){
      if (update%cdata_freq == 0) {
        for (size_t cell = 0; cell < GRID_A; ++cell) {
          channel_map_iterator = cell;
          file.Update();
        }
      }
    });

    return file;
  }
```

**Comment by mmore500** [comment]
Interested in ideas for how this might be accomplished nicely through changes to the Empirical interface...

**Comment by mercere99** [comment]
Having operator<< working seems like a great idea.  Is the goal to have this functionality behave the same as if the values being passed in were in the original file when it was loaded?

My concern is that we need to be careful when we start a new line and when we append on to the last line in the file, but I'm sure we'll be able to play with it to figure out what's most intuitive.

**Comment by mmore500** [comment]
Right now, `<<` is just writing directly to the file's output stream. I'm unsure what the best interface would be here. It seems like DataFile was designed for nice structured output and this kind of lets the user bypass that, which seems to defeat the point.

**Comment by emilydolson** [comment]
This functionality seems kind of similar to what I've been trying to accomplish with the ContainerDataFile class (https://github.com/emilydolson/Empirical/blob/alife2018/source/data/DataFile.h). The basic idea is that it has a function that returns a container (e.g. through all positions in the grid) and a set of functions that run on each individual element of that container. So the DataFile has one row per thing in the container per update.

**Comment by mmore500** [comment]
That looks like exactly what I'm looking for!

**Comment by mmore500** [comment]
I assume that'll get merged in sometime after ALife?

**Comment by emilydolson** [comment]
That was my plan, because these changes are very mildly intermixed with the changes to the systematics manager (in that both involved editing parts of World.h and I was doing them on the same branch). However, it wouldn't actually be that hard to make a pull request that just has these changes - if you need them for your ALife paper, I'd be happy to.

**Comment by mmore500** [comment]
My ugly hack works fine. After the deadline, it would be nice to publish code that works without a custom Empirical branch! But that can wait until after the deadline.

**Comment by mmore500** [comment]
I think I'll close this. Just let me know when Container DataFiles go live :)

**Comment by emilydolson** [comment]
Sounds good - we'll be doing that for our paper at that point too :)

**Pull request closed without merging**
