### PR TITLE
Measure

### PR DESCRIPTION
**Pull request by stevenjson**
This PR is to add the fully functioning stats manager to the evo library as well as the Pools PopulationManager. 

## An Overview:

The StatsManager is an addition to the evo library that controls and stores various statistics a user might need when collecting data.

The Pools PopulationManager is a new manager that creates "islands" of populations that the user can define to have various connections, both directed and undirected, on which populations can migrate. The pools are well-mixed and can be set to contain any amount of elements desired. 

- [x] Is it mergeable?
- [x] Did it pass the tests?
- [x] Does 'make doc' succeed?
- [x] If you added code, is it tested? Look at the output for 'make diff-cover'
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?
@mercere99 @bocajnotnef @emilydolson

### CODE REVIEW

**Comment by bocajnotnef** [comment]
So, the CI is failing this because vigilance is broken (ugh). I return to my cycle of trying to find an 'actual' solution that'll magically make actual diff-cover work, which would be ideal, while hacking on vigilance to make it work as a stopgap.

That said, I ran the tests manually and they all pass, though I'd like to see more test coverage on the evo library.

I'll do a more detailed review of the code later, though I don't expect there to be many/any problems.

**Comment by emilydolson** [comment]
At some point we should talk more about the examples/evo directory and what should go there. At a minimum, I think we probably don't want to include any of the shell scripts or ipython notebook, since they're specific to experiments you've been doing (unless @mercere99 disagrees). 

I suspect we're also starting to accumulate more very similar .cc files than we need, but that's a less pressing issue. For now, I'd just suggest renaming replica.cc to something that will be more intuitive to other people, and maybe cleaning up the code inside it a bit (removing the vast swaths of commented out regions that we no longer need :) ). We should probably get rid of the changes to NK.cc - I didn't mean to commit them.

I'll take a more thorough look at the rest of the code a bit later (although I think I've already seen most of it at this point).

**Comment by stevenjson** [comment]
Ok. I think I took care of everything you were concerned about Emily. Any other things that might need my attention?

**Comment by bocajnotnef** [comment]
Additional test coverage would be good. I think in a lot of cases code in
the examples/ directory can be adapted to serve as test cases for other
things in evo/--though that's probably beyond the scope of this pull.

In general I would like to avoid/minimize the merging of untested code, so
I'd say make sure tests cover all the additions you've made.

**Comment by stevenjson** [comment]
@bocajnotnef can you remove vigilance from the travis CI until you get a chance to fix it?

**Comment by bocajnotnef** [comment]
Vigilance disabled in 1dfcff04baf68aafd8e151370c5667a12f4fa041. You'll need to `git fetch; git pull origin master` for the change to take effect.

**Comment by bocajnotnef** [comment]
The tests pass and cover much of NK and the stats manager now, which makes me happy.

Looks good to me, ready for merge!

@emilydolson

**Pull request merged**
