### PR TITLE
New version of BitVector SetUInt does not match legacy behavior

### PR DESCRIPTION
**Pull request by amlalejini**
The new version of BitVector's `SetUInt` function behaves differently than the previous version that relied on casting.

Discussion of this issue happened over slack. See below for an excerpt. 

<hr/>

Dump of Slack discussion:

> For some context, here’s the current SetUInt:
```
    /// Update the 32-bit uint at the specified uint index.
    void SetUInt(size_t index, uint32_t value) {
      if constexpr (sizeof(field_t) == 4) bit_set[index] = value;
      emp_assert(sizeof(field_t) == 8);
      const size_t field_id = index/2;
      const size_t field_pos = 1 - (index & 1);
      const field_t mask = ((field_t) ((uint32_t) -1)) << (1-field_pos);
      emp_assert(field_id < NumFields());
      bit_set[field_id] &= mask;   // Clear out bits that we are setting.
      bit_set[field_id] |= ((field_t) value) << (field_pos * 32);
    }
```

> If I change how we calculate the field_id and field_pos variables as such:
```
    void SetUIntAtBit(size_t index, uint32_t value) {
      if constexpr (sizeof(field_t) == 4) bit_set[index] = value;
      emp_assert(sizeof(field_t) == 8);
      const size_t field_id = FieldID(index);
      const size_t field_pos = FieldPos(index);
      const field_t mask = ((field_t) ((uint32_t) -1)) << (1-field_pos);
      emp_assert(field_id < NumFields());
      bit_set[field_id] &= mask;   // Clear out bits that we are setting.
      bit_set[field_id] |= ((field_t) value) << (field_pos * 32);
    }
```

> This SetUIntAtBit function behaves as SetUInt it used to (at least in the way the legacy code I’m working with assumed). 

> This chunk demonstrates the difference:
```
  // Using SetUIntAtBit
  emp::BitVector vec(4);
  vec.SetUIntAtBit(0, 15);
  std::cout << "vec: ";
  vec.Print();
  std::cout << std::endl;
 
  // Using SetUInt
  emp::BitVector vec2(4);
  vec2.SetUInt(0, 15);
  std::cout << "vec2: ";
  vec2.Print();
  std::cout << std::endl;
```

> outputs:
```
vec: 1111
vec2: 0000
```

### CODE REVIEW

**Comment by amlalejini** [comment]
A couple of questions about SetUInt:

- is this difference in behavior (old version vs new version of SetUInt) expected/intentional?
- should the top if constexpr statement be an if/else?

**Comment by amlalejini** [comment]
A code snippet that uses more than one field under the bitvector hood:
```
  emp::BitVector vec3(128);
  vec3.SetUInt(0, 15);
  vec3.SetUInt(2, 15);
  std::cout << "vec3: ";
  vec3.PrintFields();
  std::cout << std::endl;
```
outputs 
```
vec3: 0 0000000000000000000000000001111000000000000000000000000000000000 000000000000000000000000000111100000000000000000000000000000000
```

**Comment by perryk12** [comment]
Matthew and I have been working on the this bug with SetUint for bitvectors. We modified the implementation of setuint for bitsets to fix the error and then also added in masking the unused leading bits.
We benchmarked each version: current and proposed, each with and without masking. This is the link to the code and results!  http://quick-bench.com/Mnmc5bzbT8bQxTWMXjYFJKGL-cg  The proposed way is much faster without a mask, but about the same as the current way with a mask.

**Comment by mmore500** [comment]
Reset to master and cherrypicked relevant commits then force-pushed (this branch originally incorporated extraneous commits from reorganize tests, my fault).

**Comment by mmore500** [comment]
We still need to write some tests: regression test on original bug pointed out by @amlalejini and new tests for changes to masking (that emp assert is thrown when we try to set uint that would write 1s to padding bits). Then should be ready to merge!

**Pull request merged**
