### PR TITLE
Add quorum orgs to the evo library

### PR DESCRIPTION
**Pull request by bocajnotnef**
This PR is for adding quorum-sensing organisms to the evo library.

Currently, all the code is in place but can't be tested since it breaks the current state of AdaptTemplate in strange ways.
## An overview:

QuorumOrganisms are a specific class of organism with parameters for probabilty to generate a signal, a threshold for % of neighbors that must be emitting the signal to attempt to co-operate, and a probability to co-operate when a quorum is detected.

QuorumManagers implement methods specific to managing QuorumOrganisms (e.g. detecting quorums). They're templated off of standard population managers to allow QuorumOrganisms to be placed onto different spatial structures with (relative) ease--all it requires is that the underlying structure has a get_neighbors() method that returns the neighbors of an organism.

Currently, it's that templating that's breaking.

### CODE REVIEW

**Comment by bocajnotnef** [comment]
Okay, so @stevenjson needs (a tiny bit of) one of the things I've added in here, and I figured I should probably merge much of this in before I get further out of sync with master, so:

TO-DO:

 - [ ] go through and purge all files that don't need to be in master
 - [ ] scan through for `@jgf` todos and make sure they're done
 - [ ] make sure the tests work, migrate some of the driver code to tests so that coverage doesn't suck
 - [ ] do interactive rebase of the commits, or just squish all of them (eek!)
 - [ ] get code review from people to make sure I didn't do The Evils
 - [ ] merge!

since @stevenjson probably needs this stuff sooner than I can get through all this I may just copy the things he needs and then employ better commit discipline (hahahahaha right).

**Comment by bocajnotnef** [comment]
Questions for working group:

Should this be merged into Empirical, or should it live in its own branch/fork as a module?
If its own branch, how to separate? lots of the stuff I've done directly modifies Empirical code. Additionally, what stuff might be worth having in Empirical?

How much of a presence should scripts (e.g. vizualizer.py) have in Empirical?

How difficult would it be to hook up a web based visualizer to a thing that replicates the experiments (e.g. `make reproduce` for paper)

**Comment by mercere99** [comment]
This pull request is drastically out of date.  Should we kill it, or do you plan to update it?

**Comment by bocajnotnef** [comment]
Probably best to just kill it.

**Pull request closed without merging**
