### PR TITLE
For `tools/random.h`, use consistent set of seeds

### PR DESCRIPTION
**Pull request by mmore500**
Tests relating to random number generator are repeated using a
set of seeds drawn from a random number generator with a
hard-coded consistent seed.

Tests not directly relating to random number generation are run
using a single hard coded seed instead of using variable system-
generated seeds.

In order to generate random positive seeds, I call
`Random.GetInt(1000000000)` because 1000000000 is the value of
`_RAND_MBIG` (internal to `Random`). This seems kludgy. Perhaps
there should be a better faculty to draw an arbitrary positive
integer from `Random`?

### CODE REVIEW

**Comment by mercere99** [comment]
Random::GetUInt() without any arguments should give you a random, 32-bit unsigned integer where all bits are randomized.  It does two draws to do this, but I think it should do the trick?

In regards to generating random number seeds, is there are reason not to just move through them successively?  A random number generate (well, a good one such as this) should give unrelated results for any change to the seed.

**Comment by mercere99** [comment]
I'm also thinking that we might want to look more into the built-in random number generators that are now in C++.  I know I thought they were a bit clunky when I looked at them originally, but they might be a better choice now, especially if we wrap them appropriately.

**Comment by mercere99** [comment]
Yep -- I think wrapping the standard library RNGs with our API would probably be the way to go.  We don't need to try that right away, and it would require a lot of testing, but certainly something we should look at when we have time.

**Comment by mmore500** [comment]
@mercere99 this should be ready to merge. At some point, we might want to check on uint64 rng tests, which seem to be failing on maybe ~1% of seeds. I suspect that is due to bookkeeping/precision issues due to the numerical magnitude of uint64s however it might be due to some sort of issue with correlation between uint32 successive draws that are stitched together to make a uint64 rng draw (?) or some other issue.

**Comment by mmore500** [comment]
I did some back-of-the napkin math and our expected failure rate should be approx 1 in 1744278. Clearly, we're observing more failures than expected. However, this PR doesn't directly relate to the uint64 implementation or their tests. I think we should merge this in and open a new issue to figure out why uint64 rng tests are failing more often than expected and rewrite them to fix it (or if there's an underlying bug in the implementation, fix that).

**Pull request merged**
