### PR TITLE
Prototype/chlogdir

### PR DESCRIPTION
**Pull request by bocajnotnef**
So, one problem: this is done based on filename order, not any kind of date;

so if I make pr # 6 and # 7, but 7 gets merged before 6 that won't be reflected in the changelog. It'll look like 6 was always before 7.

I don't currently have a good way of avoiding this problem. Open to suggestions.

### CODE REVIEW

**Comment by bocajnotnef** [comment]
Also,
 - [ ] add changelog to docs (if we think this is a good thing to do)

**Comment by mercere99** [comment]
I wonder if we could have a script run with every comment.  Thus we just have a single new changes file, that automatically gets appended to ChangeLog when a commit is finalized.

**Comment by bocajnotnef** [comment]
Hmm. Could probably hack something together from the git log, but I feel
like automating it defeats the purpose of having a change log. To me, it's
to have a human review the changes and give a reason for each of them,
keeping PRs semi-sane for reviewers.

**Comment by mercere99** [comment]
I think I didn't explain myself well --
What if when you setup a pull request, you include an extra file with that pull request which is the new pieces for the ChangeLog.  That extra file gets reveiwed, etc, and when the pull request is accepted, an automated script would grab the new file, prepend it to the ChangeLog, and delete the original.  Thus the ChangeLog only gets updated when a pull request is accepted and everything is kept in the correct order, while full details still being reviewed.

**Comment by bocajnotnef** [comment]
Logistically I'm not sure how to structure that kind of a script--the pieces would have to be prepended immediately prior to the merge. I don't know of a way to trigger a script that'd run on a merge to master that would also be safe (plus, would double the # of commits to master, which seems silly), and if the prepending was done a while ahead of the merge then other changes could sneak into the master ChangeLog, which would cause a merge conflict which would defeat the purpose of doing it this way anyway.

I like the idea of there being a separate file for each PR containing the details of what's added there (though it might pollute the project with 'unnecessary' commentary files) that then get compiled into a ChangeLog, but it seems redundant in the face of a single running changelog.

**Pull request closed without merging**
