### PR TITLE
MatchBin Housekeeping & Optimization

### PR DESCRIPTION
**Pull request by mmore500**

### CODE REVIEW

**Comment by mmore500** [comment]
key changes/additions:

*  make Empirical compatible running on an Emscripten pthread off of the main browser thread
  * changing most `EM_ASM` calls to `MAIN_THREAD_EM_ASM` calls
  * writing a special optimization for Canvas so that we can do work on `OffscreenCanvas`es and then send them over to the main browser thread
  * forwarding callback to webworker in Phread mode 
    * <https://github.com/devosoft/Empirical/blob/af42d37934d7d947d0e46221194e75a2928f9e5d/include/emp/web/JSWrap.hpp#L538>
    * <https://github.com/devosoft/Empirical/blob/af42d37934d7d947d0e46221194e75a2928f9e5d/include/emp/web/JSWrap.hpp#L583>
   * implement TextFeed object that specializes in the scenario where you want to repeatedly add text to a web page (for performance reasons, useful for on screen log)

* matchbin optimizations
  * add MatchDepository implementation --- like a MatchBin, but can go faster because it assumes nothing will be removed from it
  * port SmallVector implementation from Clang

* migrate from Travis to GitHub Actions for CI
  * <https://github.com/devosoft/Empirical/blob/small-vector/.github/workflows/CI.yml>
  * pluses: can run 20 jobs in parallel, jobs can run up to 6 hours without timing out, now everything's consolidated on GitHub
  * minuses: live streaming of job progress isn't as good, not as good of an interface for canceling individual job components, now everything's riding on GitHub

**Review by mercere99 — CHANGES_REQUESTED** [review]
Third party files added to include/emp/ should either be incorporated into Empirical style IF we think we will use them more broadly or else put into the third-party directory if they are just there to support something else.

For moving into Empirical style, header should be updated (and describe what the class is used for), include guards should be setup, and other aspects of style should be used (such as tabbing).

AssociativeArrayCache.hpp  also needs a proper header (with description) and include guards.  Perhaps come up with a more intuitive name for this, based on what it does?  ArrayMap?  SmallMap?
- Perhaps also add operator[] functionality.

In type_traits, spell out ADL (and possibly explain if not clear).

We should probably have an explanation of exactly how "empCppCallback" and "empDoCppCallback" differ since it's not really clear from the name.

**Comment by mmore500** [comment]
RE: our conversation, I did a little more digging and the the only overhead of `MAIN_THREAD_EM_ASM` vs `MAIN_THREAD_EM_ASM` appears to be a check against `ENVIRONMENT_IS_PTHREAD` (https://github.com/emscripten-core/emscripten/blob/3f7d8eeac3c3a650d99f41a15621ceabec4f43d4/src/shell_pthreads.js) so the runtime cost should be negligible.

**Comment by mmore500** [comment]
Renamed `AssociativeArrayCache` to `SmallFifoMap`

**Pull request merged**
