### PR TITLE
Test ProjectTemplate

### PR DESCRIPTION
**Pull request by mmore500**
As mentioned by @mercere99 in #230 , we should test the ProjectTemplate in automated tests... I think I'm partway to a solution but not all the way there yet.

The general idea is that we provide a `make test` Makefile directive in the `/examples/ProjectTemplate` directory that triggers web/native compile and a really simple web/native test. I've included commands to test the native executable...

```
test: clean debug debug-web
	./project_name | grep -q 'Hello, world!' && echo 'matched!' || exit 1
```

... but I'm still trying to figure out how to test the javascript executable. It seems like Node would be the way to do this... but because we're using `emp::Document` in the web hello world we need a window-ed environment and Jquery in order to run the javascript executable. Here's the general outline of what I toyed around with but couldn't quite get to work.

```
sed -i '1iTODO javascript code to load jsdom and jquery' web/project_name.js && node web/project_name.js | grep -q "Hello, console!" && echo 'matched!' || exit 1
```

We would also need to hook this `/examples/ProjectTemplate` into the .travis.yml job list.

Thoughts/advice here much appreciated!!

### CODE REVIEW

**Comment by mmore500** [comment]
Maybe @emilydolson has some wisdom about how to proceed with the web tests via node here? I tried 

```
$(CXX_web) $(CFLAGS_web) source/web/project_name-web.cc -o test-project_name.js
node test-project_name.js | grep -q "Hello, console!" && echo 'matched!' || exit 1
```

as in the `tests/web/Makefile` entry for `test_visualizations.js` but couldn't get a successful run of the `.js` file with node because `$` is not defined (e.g., jquery isn't loaded).

**Comment by mmore500** [comment]
I tried inserting

```
var jsdom = require('jsdom');
const { JSDOM } = jsdom;
const { window } = new JSDOM();
const { document } = (new JSDOM('')).window;
global.document = document;

var $ = jQuery = require('jquery')(window);
```

at the front of the `web/project_name.js` file... but this made loading the WASM fail
```
both async and sync fetching of the wasm failed
both async and sync fetching of the wasm failed
failed to asynchronously prepare wasm: abort("both async and sync fetching of the wasm failed"). Build with -s ASSERTIONS=1 for more info.
abort("both async and sync fetching of the wasm failed"). Build with -s ASSERTIONS=1 for more info.
abort("both async and sync fetching of the wasm failed"). Build with -s ASSERTIONS=1 for more info.

(node:24774) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): abort("abort(\"both async and sync fetching of the wasm failed\"). Build with -s ASSERTIONS=1 for more info."). Build with -s ASSERTIONS=1 for more info.
(node:24774) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mmore500** [comment]
Maybe CheerioJS ([https://github.com/cheeriojs/cheerio](https://github.com/cheeriojs/cheerio)) could be helpful for making JQuery play nice in node.

**Comment by mmore500** [comment]
I tried pre-pending with
```
const { JSDOM } = require('jsdom');

const jsdom = new JSDOM('<!doctype html> <html> <head> <meta charset="utf-8"> <title>Project Name</title> </head> <body> <div id="emp_base"></div> <script src="jquery-1.11.2.min.js"></script> <script type="text/javascript" src="project_name.js"></script> </body> </html>');
const { window } = jsdom;

function copyProps(src, target) {
  Object.defineProperties(target, {
    ...Object.getOwnPropertyDescriptors(src),
    ...Object.getOwnPropertyDescriptors(target),
  });
}

global.window = window;
global.document = window.document;
global.navigator = {
  userAgent: 'node.js',
};
global.requestAnimationFrame = function (callback) {
  return setTimeout(callback, 0);
};
global.cancelAnimationFrame = function (id) {
  clearTimeout(id);
};
copyProps(window, global);

const cheerio = require('cheerio')
const $ = cheerio.load('<h2 class="title">Hello world</h2>')
```
and ran into the same WASM fail. Using `-s WASM=0`, I got a new error

```
/home/mmore500/Projects/Empirical/examples/ProjectTemplate/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:480
        throw new DOMException("The string did not match the expected pattern.", "SyntaxError");
        ^
SyntaxError: The string did not match the expected pattern.
    at XMLHttpRequest.open (/home/mmore500/Projects/Empirical/examples/ProjectTemplate/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:480:15)
    at Object.readAsync (/home/mmore500/Projects/Empirical/examples/ProjectTemplate/web/project_name.js:172:7)
    at doBrowserLoad (/home/mmore500/Projects/Empirical/examples/ProjectTemplate/web/project_name.js:5209:23)
    at Object.<anonymous> (/home/mmore500/Projects/Empirical/examples/ProjectTemplate/web/project_name.js:5230:4)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
```

which seems related to loading up asm.js resources.

**Comment by mmore500** [comment]
I've been able to get Node to run compiled Javascript without jquery dependencies, but no luck with our jquery dependency.

**Comment by emilydolson** [comment]
This is a great idea! I'd also love to include a template .travis.yml file in the template.

I haven't looked at this in a while, but here's how the current tests work. There are two sets of web tests in Empirical, one for things that require a DOM and one for things that don't. I believe the ones that don't require the DOM are being run using Node (the command is in run_tests.sh in the tests/web directory).

For the ones that require a DOM, I tried a ton of things and eventually gave up and just had them run in Firefox. Travis supports Firefox for this exact reason. That's why test_visualizations isn't happy when you try to run it in Node. There's a whole set up with a testing framework and a test runner, which is documented in a post on the lab blog.

**Comment by mmore500** [comment]
:/ unfortunately the lab blog is still down

**Comment by mmore500** [comment]
I pushed a possible phantomjs implementation, which spits out the rendered HTML to be checked against a gold standard and then the console output to be checked against a gold standard.

The phantomjs implementation isn't ideal because it adds a new dependency (and a dead one at that). It may be possible to re-implement with nodejs puppeteer (aka headless chrome). Once the lab blog is back up, I'll take a look in more detail at how our Firefox tests are set up and see about maybe hooking directly into that instead.

**Comment by mmore500** [comment]
Switched to a node-based test, which uses the package puppeteer.

**Comment by mmore500** [comment]
I put together a minimal working example of using puppeteer with TravisCI here: [https://github.com/mmore500/mwe-travis-puppeteer](https://github.com/mmore500/mwe-travis-puppeteer)... the build is passing! Looks like we have all the puzzle pieces in place to test ProjectTemplate.

**Comment by mmore500** [comment]
It builds!!! And bouncing off @emilydolson I included an example `.travis.yml` file.

**Comment by mmore500** [comment]
Ready for review!

**Comment by mmore500** [comment]
We should reconsider this in light of the cookiecutter project template.

**Comment by emilydolson** [comment]
In that we should be encouraging people to use the cookie-cutter template instead of this?

**Comment by mmore500** [comment]
Exactly. And if we kill ProjectTemplate we don't have to test it. Maybe for the Empirical CI testing we should do the following instead:1. clone cookiecutter template2. Instantiate a cookiecutter project3. compile the cookiecutter project with the Empirical source being run through the CI4. run the instantiated project's tests and make sure they passWe would also have to rewrite the "Hello World" quickstart to refer to the cookiecutter template instead of ProjectTemplate.                                                                                                                                                                                                                                                                                                                                         Matthew Andres Morenohttps://mmore500.github.io                                                                                                                                                                                                                From: Emily DolsonSent: Wednesday, April 24, 2019 1:23 PMTo: devosoft/EmpiricalReply To: devosoft/EmpiricalCc: Matthew Andres Moreno; AuthorSubject: Re: [devosoft/Empirical] Test ProjectTemplate (#231)In that we should be encouraging people to use the cookie-cutter template instead of this?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/devosoft/Empirical","title":"devosoft/Empirical","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/devosoft/Empirical"}},"updates":{"snippets":[{"icon":"PERSON","message":"@emilydolson in #231: In that we should be encouraging people to use the cookie-cutter template instead of this?"}],"action":{"name":"View Pull Request","url":"https://github.com/devosoft/Empirical/pull/231#issuecomment-486341834"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/devosoft/Empirical/pull/231#issuecomment-486341834",
"url": "https://github.com/devosoft/Empirical/pull/231#issuecomment-486341834",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by emilydolson** [comment]
I am 100% in favor of that idea. The cookie-cutter template seems like a strictly better version of ProjectTemplate (since you can easily screw up ProjectTemplate by not making all the necessary changes). The only downside I see is that it's an additional dependency for people who want to use the template. But I think it's worth it. And that sounds like a great way to do the testing!

Thinking a bit more about the general question of what testing we want to include in the template: It looks like this pupeteer setup handles most of what the average user of the project template would need (i.e. does the page have generally the right stuff on it). Adding the full Javascript testing framework would add a lot of dependencies, and it's not the easiest thing to get started with. The benefit of it is that it allows us to directly test the Javascript that Empirical compiles to. This is important for the core of Empirical, and I could think of instances where someone would want it for testing their project (e.g. I often write OnClick functions for specific user interactions in the web versions of projects and then break them without realizing it because I don't have tests for them). But I don't know if it's worth including in the template. Is it possible to somehow have a basic template and an advanced template?

**Comment by mmore500** [comment]
‎Agreed & that should be possible. Example, cookiecutter py project template (https://github.com/audreyr/cookiecutter-pypackage) lets you opt in/out of an entire testing suite by wrapping all the relevant code in a conditional include.                                                                                                                                                                                                   Matthew Andres Morenohttps://mmore500.github.io                                                                                                                                                                                                                From: Emily DolsonSent: Wednesday, April 24, 2019 2:22 PM‎To: devosoft/EmpiricalReply To: devosoft/EmpiricalCc: Matthew Andres Moreno; AuthorSubject: Re: [devosoft/Empirical] Test ProjectTemplate (#231)I am 100% in favor of that idea. The cookie-cutter template seems like a strictly better version of ProjectTemplate (since you can easily screw up ProjectTemplate by not making all the necessary changes). The only downside I see is that it's an additional dependency for people who want to use the template. But I think it's worth it. And that sounds like a great way to do the testing!
Thinking a bit more about the general question of what testing we want to include in the template: It looks like this pupeteer setup handles most of what the average user of the project template would need (i.e. does the page have generally the right stuff on it). Adding the full Javascript testing framework would add a lot of dependencies, and it's not the easiest thing to get started with. The benefit of it is that it allows us to directly test the Javascript that Empirical compiles to. This is important for the core of Empirical, and I could think of instances where someone would want it for testing their project (e.g. I often write OnClick functions for specific user interactions in the web versions of projects and then break them without realizing it because I don't have tests for them). But I don't know if it's worth including in the template. Is it possible to somehow have a basic template and an advanced template?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/devosoft/Empirical","title":"devosoft/Empirical","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/devosoft/Empirical"}},"updates":{"snippets":[{"icon":"PERSON","message":"@emilydolson in #231: I am 100% in favor of that idea. The cookie-cutter template seems like a strictly better version of ProjectTemplate (since you can easily screw up ProjectTemplate by not making all the necessary changes). The only downside I see is that it's an additional dependency for people who want to use the template. But I think it's worth it. And that sounds like a great way to do the testing!\r\n\r\nThinking a bit more about the general question of what testing we want to include in the template: It looks like this pupeteer setup handles most of what the average user of the project template would need (i.e. does the page have generally the right stuff on it). Adding the full Javascript testing framework would add a lot of dependencies, and it's not the easiest thing to get started with. The benefit of it is that it allows us to directly test the Javascript that Empirical compiles to. This is important for the core of Empirical, and I could think of instances where someone would want it for testing their project (e.g. I often write OnClick functions for specific user interactions in the web versions of projects and then break them without realizing it because I don't have tests for them). But I don't know if it's worth including in the template. Is it possible to somehow have a basic template and an advanced template?"}],"action":{"name":"View Pull Request","url":"https://github.com/devosoft/Empirical/pull/231#issuecomment-486369278"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/devosoft/Empirical/pull/231#issuecomment-486369278",
"url": "https://github.com/devosoft/Empirical/pull/231#issuecomment-486369278",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by mmore500** [comment]
What I ended up doing was
1. adding deprecation warnings all over ProjectTemplate so that users know to go look at cookiecutter template
2. testing that ProjectTemplate still compiles as part of Empirical's travis tests
3. instantiating the cookiecutter template and running its tests as part of Empirical's travis tests

**Comment by mmore500** [comment]
haha /finally/ ready for review @emilydolson !

**Pull request merged**
