### PR TITLE
Improvements to Empirical contribution infrastructure

### PR DESCRIPTION
**Pull request by emilydolson**
This pull request:
  -  Moves LICENSE.md to root, which is where people usually look for it.
  - Adds a CONTRIBUTING.md file with instructions for how to contribute

### CODE REVIEW

**Comment by amlalejini** [comment]
Double check that license includes all 3rd party software licenses.

**Comment by amlalejini** [comment]
Double check that we include everyone that has contributed to Empirical

**Comment by emilydolson** [comment]
@mmore500 and/or @amlalejini if one of you has a chance to look at it, this is another PR that should probably get merged before JOSS submission so that the reviewers (and users!) can easily find license and contributing information

This technically depends on #483, which is a super tiny fix that just needs someone to peek at it before it gets merged

**Review by mmore500 — APPROVED** [review]
Positive changes. Not sure why this was sitting around in limbo for 3 years. ¯\_(ツ)_/¯

**Comment by mmore500** [comment]
Looks great. Can we just merge this instead of #483 and close that PR?

**Comment by emilydolson** [comment]
Yeah, good call! Thanks for reviewing!

**Comment by emilydolson** [comment]
Wow, looks like GitHub auto-detects situations like this and automatically counted that PR as merged when I merged this one! Cool!

**Pull request merged**
