### PR TITLE
Directory reorganization

### PR DESCRIPTION
**Pull request by amlalejini**
This pull request addresses issue #378 

Major changes:
- Change .h extensions to .hpp
- Change .cc extensions to .hpp
- source/ is now include/emp/
- tests2/ has been removed
  - relocate tests2/unit_tests.hpp to include/emp/testing/
  - relocate examples of unit_tests.hpp usage to examples directory
- The source/tools/ directory has been reorganized (see issue #378)
- apps/ renamed to demos/
- Add test stubs for (non-web) headers that do not have an associated test file
  - this combats the inflated test coverage number we have (and ensures that our header files at least compile when included...)
- Remove deprecated/broken headers (e.g., constexpr headers, ActiveDataMap, etc)

### CODE REVIEW

**Comment by amlalejini** [comment]
**Before merging**:
- Tag a pre-release of existing master branch

**Review by mercere99 — COMMENTED** [review]
Some notes as I look through this (not all of which need to be fixed for THIS merge):
* We should remove no-longer-existing files from the .gitignore (especially most of the apps/)
* We should probably put Slideshow.hpp into its own folder.
* We should probably be consistent in the demos whether we include just the shortened filename (assuming an include director is provided to the compiler) or provide the full path.  For example, should we do "../../../include/emp/base/assert.hpp" or just "emp/base/assert.hpp".  Right now we have a mix.

(I've made it about 40% through, down through the doc/* ... will continue from there)

**Review by mercere99 — COMMENTED** [review]
More comments:
* In the examples/Evolve/ directory, it looks like the *.cc versions of files were removed and the *.cpp versions were added.  Elsewhere files are marked as "renamed" and I think that renaming would be safer in general for merging branches pre-refactor.  That said, these examples are not likely to have a ton of changes (or any).
* Similar issues in most other examples/ folders (though not all...)
* examples/testing/ looks good!
* We do probably want to move examples/timing/ elsewhere, probably to a top-level benchmarks/ folder.
* Its clear that the "removed" and "added" pattern (as opposed to "renamed")  is common in the shift from source/ to include/emp/ as well.  I'm much more concerned here that this change will cause lots of headaches when trying to merge in changes from an older version.  That said, I'm not sure if that would be more work or trying to fix this PR would be.  Fixing the PR would also preserve a cleaner history when needing to look back at the changes to a file.  It is strange how the "renamed" files are just mixed in with the others.
* Wow we have a lot of test files (that's great!).  So much easier now that we don't just have monolith files.
* demos/MAP-Elites-Arm/source/ArmWorld.hpp and demos/MAP-Elites-Arm/source/native/MAP-Elites-Arm.cpp need to have their @file updated.  (I see other files do too) Probably worth grepping through the rest of the repository (and especially the demos directory) to see if any others have an "@file" with a ".h" without the "pp" or a ".cc"

**Comment by amlalejini** [comment]
>  In the examples/Evolve/ directory, it looks like the *.cc versions of files were removed and the *.cpp versions were added.  Elsewhere files are marked as "renamed" and I think that renaming would be safer in general for merging branches pre-refactor.  That said, these examples are not likely to have a ton of changes (or any).

Not totally sure why some things are marked as renamed vs. added/removed. Everything got renamed and moved with `git mv` (I definitely did not do any adding/removing by hand).  

>  We do probably want to move examples/timing/ elsewhere, probably to a top-level benchmarks/ folder.

My assumption as that we'd make that change when we work on issue #387 (after this PR). 

>  Its clear that the "removed" and "added" pattern (as opposed to "renamed")  is common in the shift from source/ to include/emp/ as well.  I'm much more concerned here that this change will cause lots of headaches when trying to merge in changes from an older version.  That said, I'm not sure if that would be more work or trying to fix this PR would be.  Fixing the PR would also preserve a cleaner history when needing to look back at the changes to a file.  It is strange how the "renamed" files are just mixed in with the others.

Same here as above. I will say that I had no issues with merging the systematics updates into this PR; all of the files were updated appropriately in the correct location. 

I'm not sure how we would go about fixing the PR without substantial effort, and I'm not entirely convinced that there's anything wrong as is. 

>   demos/MAP-Elites-Arm/source/ArmWorld.hpp and demos/MAP-Elites-Arm/source/native/MAP-Elites-Arm.cpp need to have their @file updated.  (I see other files do too) Probably worth grepping through the rest of the repository (and especially the demos directory) to see if any others have an "@file" with a ".h" without the "pp" or a ".cc"

I fixed Map-Elites-Arm.cpp, Map-Elites-Arm-web.cpp, and ArmWorld.hpp. I'm not seeing anything else? It looks like the vast majority of demos don't have an @file tag. There are certainly random one-off comments throughout the library that make reference to .h files that I did not edit. I think I'll pass the baton on that one if we want to do it for this PR; otherwise, I figured we correct those as we come across them.

**Comment by amlalejini** [comment]
RE: the file renaming thing

I think git knows what's up under the hood: https://github.com/devosoft/Empirical/pull/379/commits/546abd32eed30ae1378101ff4c70438db5a28f2c

**Review by mercere99 — APPROVED** [review]
Everything looks good to me!

**Pull request merged**
