### PR TITLE
Add Parser for Url Query Params

### PR DESCRIPTION
**Pull request by mmore500**
Let's make it easy to snag the query params of the current web page over to the C++ side of things!

(background info: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams)

usage example:
```
#include <unordered_map>

#include "web/web.h"
#include "web/UrlParams.h"

namespace UI = emp::web;

UI::Document doc("emp_base");

int main()
{

  auto params = UI::GetUrlParams();

  for(auto & pair : params) {
    std::cout << pair.first << " -> " << pair.second << std::endl;
  }

}
```

For example, browsing to `https://example.com/example.html?foo=bar&bip=bop` would cause to the following to be output to the console.

```
bip -> bop
foo -> bar
```

### CODE REVIEW

**Comment by mmore500** [comment]
Still need to write tests for Travis, but I have it working locally.

**Comment by mercere99** [comment]
This addition is great!  Last time I looked (which was years ago) it wasn't possible to get the URL args.  They could tie into the command-line parameter system quite cleanly.

Would it make sense to put the code that takes a string that represents a URL and put it in the config directory?  Actually retrieving the URL used will require Emscripten and thus be in the web directory.  The question comes down to if we want to be able to process URLs from a non-web based app.

(We can always add this functionality where it is and then refactor later).

**Comment by mmore500** [comment]
I added test for GetUrlParams (requires NodeJS version 10+) and fixed a missing include revealed by the tests.

**Comment by mmore500** [comment]
It's nice to run the URL parsing only on the web side... because the Javascript built-ins do all the actual work! :wink: It might be useful to provide some functionality in the `/web/UrlParams.h` file that fills in / adjusts a Config object based on the URL parameter input (e.g., analogously to `source/config/ArgManager.h`).

**Comment by mmore500** [comment]
What (I assume) we want: to be able to use URL query params and command line arguments almost interchangeably to configure a Config object at runtime.

One route to this objective: have `GetURLParams` return a `ArgManager` object.

An `ArgManager` object can already easily be constructed from `argc`/`argv`. The `ArgManger` object already can set up a `Config` object via its `ProcessConfigOptions` method.

However, under the hood, the `ArgManager` represents state in a manner that is specific to the command line domain: as `vector<std::string>`. 

Proposal: Either create a new class or modify `ArgManager` to have a more generic under-the-hood representation of config options, perhaps `std::unordered_map<std::string,std::vector<std::string>>`.
* Flags:  map a key to an empty vector.
* Single value config options: map a key to a vector of size 1.
* Multi value config options: map a key to a vector of appropriate size.
We check for duplicate key values on construction and optionally throw some kind of warning or error then (instead of how I believe things are currently done where we just check for unused args at the end of processing them and pulling them out when we use them). 

Alternately, we could jury rig a shim where we spit use the existing representation for `ArgManager` and basically append `-`'s to the key values `GetUrlParams` returns.

Thoughts?

**Comment by mmore500** [comment]
I've rewritten `ArgManager` and just pushed some updates to this RE: those changes. We should merge in #238 first, update this branch, and then merge this branch in.

**Pull request merged**
