### PR TITLE
The attribute packs library

### PR DESCRIPTION
**Pull request by grenewode**
# Questions / TODOs:

- [x] Are there any stylistic conflicts? 
- [ ] How efficient is this compared to native structs?
- [ ] Implement loading/saving to JSON
- [ ] Add more documentation and comments
- [ ] Anything else people want

### CODE REVIEW

**Comment by mercere99** [comment]
These are looking like good changes.  Probably a few questions though.  One: does DEFINE_ATTR really need two arguments, or can we get away with just one?  It seems like we just need a single camel-case name?

**Comment by mercere99** [comment]
More general comment about style: we tend to use all lower case for variable names (not camel case starting with lower).

**Comment by mercere99** [comment]
One final question (for now), does anyone know why it still says "Some checks haven't completed yet"?  It there some way to get it to stop and try again?  I'm concerned that we're having trouble with our unit test system.

**Comment by emilydolson** [comment]
That's weird, there's no record of Travis trying to run this pull request, despite the fact that it ran all of the other recent ones.

Maybe it's because it's waiting for you to resolve the merge conflict in tests/test_tools.cc?

**Comment by mercere99** [comment]
Ah, possibly.

I'm currently trying to fix test_tools.  The current instantiation locks up on me ~80% of the time.  I removed the BitVector test (which I haven't touched anything related to in a while, I think, but I'll dig through the logs soon) and it works every time...

**Comment by mercere99** [comment]
Is it possible that it tried to run the tests, but the entire process froze up so it wasn't able to record any progress?

**Comment by emilydolson** [comment]
That's what I was expecting it to be, but if that had happened there would be a record on Travis of it attempting to build everything and run the tests (and then timing out after 10 minutes of it hanging).

Oddly, I am no longer able to get test_tools to hang for me. I really don't think I changed anything.

**Comment by grenewode** [comment]
`DEFINE_ATTR` does not necessarily need two arguments. One will work just fine, but it will mean that either 
1. The attribute creation function will need a new name, (eg `foo(100)` becomes `makeFoo(100)`) or the attribute marker class will need to be renamed (eg, `Foo::get(value)` becomes `FooAttr::get(value)`). 
2. I could do something like this:
    ```cpp
    constexpr struct {
        template<typename T>
        constexpr FooValue<std::decay_t<T>> operator()(T&& value) const { return ...; }
        template<typename T>
        constexpr decltype(auto) get(const FooValue<T>& value) const { return value.get(); }
        ...
    } foo;
    ```
    which combines the attribute creation function and the accessor into a single entity. I think I tend to prefer this solution, since it will make the names more consistent with everything else. Also, it allows things like
    ```cpp
    template<typename T>
    auto doSomething(const T& attribute) {
        attribute.get(...);
    }
    ```

**Comment by grenewode** [comment]
Regarding the variable names, do you mean `likethis` instead of `likeThis`?

**Comment by grenewode** [comment]
Finally, I think that the non-germane changes you noticed were probably done by my autoformatter. I should be able to revert those changes in the commits that have them, but I wonder if it might be more effective to just define an official style for [`clang-format`](https://clang.llvm.org/docs/ClangFormat.html) and commit it into the repository.

**Comment by grenewode** [comment]
Currently, builds are failing because of #147, but hopefully that will be fixed by  #148

**Comment by mercere99** [comment]
Back to looking through this pull request! (my head fills up quickly with all of this...).  In any case, I'm working on type_traits.h:
* It looks like the templates defined in the detail namespace are generally useful.  Is there are reason these shouldn't be directly in emp?
* Is there a reason that the namespace __impl_variadics_type_traits shouldn't just be an anonymous namespace?  It looks like this implementation code is only used in this file.  Also, since it's confined to the file (and thus not directly part of the Empirical API), I'm less concerned about matching the std naming convention.
* You suggest that maybe parts of this should be in their own file; I'm not sure where this code should go or how the overall meta/ folder should be organized.  For now, I'm fine with it all being in type_traits, but this might be a topic for future conversation.
* There's also some duplicate functionality now with other portions of Empirical (such as identifying unique traits, TypePack functionality, etc). I suspect that in most cases your versions are more flexible, but this is something we should also keep in mind as we go forward.  Your version of dealing with Variadics is particularly neat.

**Comment by grenewode** [comment]
1. The detail namespace holds implementation stuff which is exposed by `emp::is_invocable` in [`type_traits.h`](https://github.com/devosoft/Empirical/pull/135/files#diff-ba7cf1bda086de3241eeb3a8885b516dR87). It is needed because I have to use `decltype(detail::is_invocable::value())` to actually determine if the target is callable. In the future this whole thing should be replaced with [std::is_invocable](http://en.cppreference.com/w/cpp/types/is_invocable), but that needs c++17
2. The `__impl...` namespaces are acting as unnamed namespaces. However, I think? that actual unnamed namespaces in headers is the same as using no namespace at all, since all the empirical headers will end up the same translation unit (My understanding is based on [this](http://en.cppreference.com/w/cpp/language/namespace#Unnamed_namespaces) and [this](https://stackoverflow.com/questions/1106149/what-is-a-translation-unit-in-c))

Regarding the duplicate functionality, I agree that most of the new stuff in `type_traits.h` should be put into `TypePack`, or `TypePack` should use these functions, but I didn't want to roll too much into this pull request.

**Comment by mercere99** [comment]
The __impl namespace should work fine; I was more curious about the decision.  Turns out that I was misunderstanding how anonymous namespaces work (which I thought were limited to file, for some reason, not compilation unit).  Now I'll go fix a bunch of other stuff... ;-)

I'm not worried about fixing the duplicate functionality right away, just mentioning it's something we should figure out a good way to do.

**Pull request merged**
