### PR TITLE
Updates to systematics manager + auto-GUI for configs + sundry other updates

### PR DESCRIPTION
**Pull request by emilydolson**
Okay, it's finally happening - I'm preparing to merge the systematics stuff (plus all the tweaks I've been making during my postdoc). This is not ready for merge yet, just the initial results of merging master into my fork.

### CODE REVIEW

**Comment by emilydolson** [comment]
Full list of changes for all files except Systematics.h, which was dramatically overhauled:

**NK.h**
- Added function to query a landscape for the fitness contribution of a specific site in a specific bitstring

**OEE.h, World_output.h, testOEE.cc**
- These add the MODES metrics, which had apparently never been added to the master branch of Empirical. Was there a reason for that? Were we thinking they should be a standalone tool in a different repo?

**Resource.h**
- A change to resource select adding a configurable minimum score

**SystematicsAnalysis.h**
- Add FindDominant function
- Streamline CountUniquePhenotypes function

**set_utils.h**
- Make sure sets are passed by reference (speed) and vectors are passed by value (since they have to get sorted and so will change)

**vector_utils.h**
- Added NRange function, which generates vector containing a sequence of numbers in a range
- Added a RemoveDuplicates function, which takes a vector and returns a copy with all duplicates removed (does not preserve order)
- Made Has pass-by-value (is there a reason it wasn't already?)

**string_utils.h**
- Added functions to convert string to titlecase, count occurences of a character in a string, and one duplicating Python's str.join() method.

**stats.h**:
- Added a median function
- Replaced iterator in Shannon Entropy with a reference

**math.h**:
- Added a factorial function

**distances.h**:
- Added a new file for storing different distance metric functions. Currently only contains Euclidean.

**Random.h**:
- Added GetRandGeometric function, which pulls a random value from a geometric distribution

**Graph.h**:
- Added optional labels to nodes
- Added function to calculate a node's in-degree
- Added accessors for nodes and weights

**File.h**:
- Added a function to return a vector of all lines in the file (like Python file.readlines())

**BitSorter.h**:
- Added comparison operators to bitsorter

**AvidaGP.h**:
- Added [] operator that returns instruction
- Added size getter for compatibility with other tools
- Added << operator
- Added != operator

**color_map.h**:
- Add extra info to asserts

**DataManager.h**:
- Added additional debug information to asserts

**tests/test_tools.cc**:
- Added tests for new functions

**map_utils.h**:
- Added keys function that returns a vector containing all keys in a map

**DataNode.h**:
- Histograms now track number of values that were above or below the allowed range.

**DataFile.h**:
- Fixed bug where adding all stats at once resets nodes in between stats
- Added function to add all bins of a histogram DataNode to file
- Added ability to add functions that are run before each line of the datafile is calculated

**Style.h**:
- Gave style object the ability to handle which CSS classes are applied to an object as well

**Widget.h**:
- Added functions to handle applying classes to widgets

**config_web_interface.h**:
- A class that automatically generates a web  UI based on a config object

**config.h**:
- Changes to allow web interface to work

**test_config.cc**:
- Minor tests for config GUI

**test_evo.cc**:
- De-constify orgs

**scales.h**:
- Make it possible to pass a string into a D3 scale

**spatial_stats.h**:
- Some preliminary spatial statistics

**Input.h**:
- I did stuff to auto-format inputs but Alex has reported a problem with this so we should check it out

**World.h**:
- Added a function that adds a systematics manager by constructing it within the world (rather than passing a pointer)
- Adjusted interface to systematics in light of the fact that the systematics manager now understands WorldPositions
- Swapped org removal to occur after reproduction, to avoid issues with synchronous generations

**Comment by emilydolson** [comment]
Open questions in my mind:
- Should we add the MODES metric to Empirical or give them their own repo?
- Are the distance and spatial_stats files a good idea, or is code for this already living somewhere else?
- What exactly went wrong with Input.h when @amlalejini used it and how do we fix it?
- Is the stuff I'm doing with classes in Style and Widget deeply flawed in some way?
- Any objections to the changes to DataNode and DataFile?
- Is there something horribly wrong with the pass-by-reference stuff I added to vector_utils and set_utils?
- Is there anything horribly wrong with the modifications to the systematics manager?

I think that's the main stuff I could see being controversial. Most of the rest is just minor feature additions.

**Comment by emilydolson** [comment]
Oh, also this fixes #198

**Comment by emilydolson** [comment]
And it fixes #33!

**Comment by mercere99** [comment]
Why did you switch Has() in vector_utils.h to pass vectors by value?  That means that you now need to copy the entire vector every time you want to check if it contains a single element.

To answer your specific questions:
* I think we should probably split all of the evolution tools out of Empricial proper since they're specific to one field of research.  That said, I don't think there's a huge problem having them there.  There is some more reason to have MODES outside of Empirical if we want to be able to easily advertise those tools on their own.  Note also that all of the evolution functionality is being incorporated into MABE2, which I aim to make easier to use in every way.  So perhaps we should leave the evolution tools in Empirical for now, and if MABE2 eventually does hit our vision for it, we deprecate them.

* We should think about how a number of these organizations should go.  In regard to distances, we do have things like Hamming distance implemented in sequence.h, but Euclidean distance shouldn't really go there.  Where it DOES belong is the geometry/ folder.  In fact, Point2D.h does have Euclidean distance baked into it, but is limited to two dimensions.

* I'll have to look at Input.h ... I'm not remembering what it's even supposed to be.

* My inclination for dealing with CSS classes is to have an object for them, even if they're just a string under the hood.  This will allow us to hook up more direct functionality.  That said, this could be a fix that we do later; I think it should work fine as a string for now.

* Changes to DataNode and DataFile make sense and look good to me.

* Changes to set_utils make sense (it was broken before).  As I mentioned at the beginning, I don't understand your change to Has() in vector_utils.

* I don't see obvious problems with the changes to systematics, but there are a lot of them and I must admit that I'm not awake enough to go through them in detail right now...

**Comment by emilydolson** [comment]
- Totally agree on vector_utils Has()! I just switched it back. I think it was a debugging thing that snuck by me because I'd just been staring at the changes to set_utils.

- That all makes sense about MODES! So should I leave them in for now and then we can split them back out when the great MABE 2.0 restructuring happens?

- Should I move distances.h to the geometry folder, then, or do we want to think more about whether it should exist at all? The reason I wrote it is that I caught myself writing generic version of Euclidean distance repeatedly and figured I should centralize it (and I do expect that Manhattan distance and the like would be similarly useful).

- Input.h is just a wrapper around HTML input objects. The changes I made were to make the auto config GUI look better, but I know that they caused some problems for Alex (since he's been using stuff from this branch for a while now), so I'm going to talk through them with him before merging this.

- That sounds like a good long-term plan for CSS classes

- Yeah, that's fair on the changes to systematics. I would also like to go through them more carefully before merging, because I haven't looked at them super recently myself. I'm sure there are some rough edges in there. That said, I have some baseline level of confidence in them because: 1) they definitely fix some bugs that are in the current master branch (hopefully without creating new ones in the process...), 2) I think I've run all the conceptual decisions by you at some point over the past couple years, 3) Alex and I have both been using them for the past two years, 4) there are pretty thorough tests, and 5) it looks like Abby is going to be working on cleaning up/documenting/extending the systematics manager for her WAVES project, so that will be an additional layer of scrutiny.

**Comment by emilydolson** [comment]
Well I guess now this fixes #37 too

**Comment by amlalejini** [comment]
RE: Input.h

Right, I ran into issues with the Input object automatically nesting the input element inside of a form element (see `GetHTML` in Input.h). I'm pretty sure I was trying to use Bootstrap's input group features to control styling, and the form element around every input element was wonking the bootstrap styling.

One easy fix would be to make the form element (and the extra output element) a non-default thing you can toggle on. However, I'm not sure I'm in favor of this fix.

Instead, I am generally in favor of each of the Empirical classes that represent 'atomic' web elements (e.g., Div, Input, etc) managing _only_ the html relevant to that web element. When someone adds an Input element to their document, I think it's more intuitive to expect only an input element will be added. I would be in favor of making wrappers/derived classes for more complicated html constructions (e.g., a form-nested input). 

Thoughts?

**Comment by emilydolson** [comment]
You're right - that's a much more consistent way to do this. I'll refactor and create a separate form element if necessary.

**Comment by emilydolson** [comment]
@amlalejini looking through what I changed in Input.h, I'm seeing I added three different HTML elements in addition to the element. One is the form, which I absolutely agree should go elsewhere (I'm thinking I'll move it to the config UI class). The other two I'm less sure about. They're a label element and an output element, and both are optional. I know it violates the "one class one HTML element" policy to leave them there, but even in normal HTML label and output elements are very closely associated with input elements. If you want an input, there's a very good chance that you also want a label and/or output, and having to manually make C++ objects for all of them seems cumbersome. As such, I'm tempted to leave them. Thoughts?

**Comment by amlalejini** [comment]
If you include them, is it easy to access both the output and label element attributes/style with the SetAttr and SetCSS functions on the C++ side? My understanding is that neither are represented as widget objects, so we'd have to use js to select them for post-hoc manipulation? We could insert actual UI::Element's instead of elements embedded in plain strings.

I'm still in favor of not including them. But, as long as they're optional (my preference would be to require users to opt-in instead of opt-out), I don't have an issue with them. Maybe `show_value` should instead be something like `attach_output`?

**Comment by emilydolson** [comment]
Good points. I definitely like the idea of making them be proper web::Elements that are accessible with setters and getters so you can see the CSS and such. I also totally agree on turning them off by default (already fixed that) and renaming show_value to attach_output.

I think the reason I'm so in favor of leaving them (optionally) in the input class is that you would never make an output or label that wasn't associated with an input. So making them be their own classes doesn't make a lot of sense. And forcing the user to make them with element objects every time is a lot of extra boilerplate for a relatively common goal. It seems like this best conforms to the principle of making the common use case easy.

That said, I'm happy to be convinced otherwise. One compromise could be to make a new class built on top of the Input class that provides the additional elements. But that seems like a fair amount of additional code without much tangible benefit.

**Comment by amlalejini** [comment]
If the new class is derived from Input, would it need replicate much more than the GetHTML function? 

Given all the changes discussed, I'm not strongly against including optional label/output elements in the Input class. All of my general use cases for Input.h are covered now. 

I do think the most future-proof thing we can do is to have the atomic html elements be minimal, so that composing new standard groupings of elements (e.g., if future us wants to build support for future fancy javascript/layout managers that aren't bootstrap). That said, keeping optional label/output, doesn't really box us in; it just might make the full signatures for future compositions be a little bloated. My instincts here could be totally off, though.

As other heavy users of the web infrastructure, @mmore500 and @mercere99 might have opinions?

**Comment by mmore500** [comment]
I wonder if we want to keep atomic web elements inside web/ and start a new subfolder for composites built from atomics? I’m wondering for example whether config/config_web_interface.h might be better suited to that sort of location. We could put layout managers and composites here (I’ve been wanting to make one for a “data pill” that provides a readout and title with a collapsible description)

**Comment by mmore500** [comment]
Possible names in no particular order: gizmo, prefab, readymade, blocks, composite, composition, pieces, ensemble(s), plugnplay

**Comment by mmore500** [comment]
I kind of like prefab

**Comment by emilydolson** [comment]
I like prefab too! And I agree that that would be a better home for config_web_interface.h as well.

**Comment by amlalejini** [comment]
Also love both the name 'prefab' and the idea of having a dedicated prefab directory!

**Comment by emilydolson** [comment]
Okay, so I messed around with creating a LabelledInput class that inherits from Input and it's less straightforward than I expected. The inheritance gets messy fast because of the need for the LabelledInputInfo class to inherit from the InputInfo class. I think the right way to do it would be to have the LabelledInput class not inherit from Input and instead have a member variable holding an Input and two others holding elements for the label and output. But then I'm not sure how to make the correct TriggerJS happen.

Since the current version works and isn't obviously not how we want to do it, I'm going to argue that we should merge it in the interest of not holding up other pull requests that depend on this one. If someone want to refactor Input to be truly atomic in the future I will 100% support that endeavour.

**Pull request merged**
