### PR TITLE
Draft HtmlDataFile, JsonDataFile (RE: issue #111)

### PR DESCRIPTION
**Pull request by mmore500**
TODO:
- [ ] how to integrate with ContainerDataFile?
- [ ] how to handle inheritance/delegated constructors to provide constructors for HtmlDataFile and JsonDataFile that take an arbitrary output stream (instead of a filename)?
   * need some advice/help on this
- [ ] some remaining documentation TODO's

### CODE REVIEW

**Comment by mmore500** [comment]
I added a cool third party dependency for json magic: [https://github.com/nlohmann/json](https://github.com/nlohmann/json).

**Comment by mmore500** [comment]
Test cases give a good idea of how HtmlDataFile and JsonDataFile, which inherit from DataFile, are used:
```
TEST_CASE("Test JsonDataFile", "[data]") {

    // emp::JsonDataFile needs to go out of scope
    // in order to have the destructor called
    // in order to have the finishing touches applied
    // for a valid JSON file
    {
      emp::JsonDataFile dfile("test_json_file.json");

      emp::DataMonitor<double> data_fracs;
      emp::DataMonitor<int> data_squares;
      emp::DataMonitor<uint64_t> data_cubes;

      std::function<nlohmann::json(void)> test_json = [](){
        nlohmann::json j;
        j["val"] = 5;
        j["yes"] = "please";
        j["no"] = "thanks";
        return j;
      };

      int test_int = 5;
      auto test_fun = [](){
        static int val = 10;
        return val += 3;
      };

      dfile.AddCurrent(data_fracs,"data_fracs_Current","TODO");
      dfile.AddCurrent(data_squares,"data_squares_Current","TODO");
      dfile.AddCurrent(data_cubes,"data_cubes_Current","TODO");
      dfile.AddMean(data_cubes,"data_cubes_Mean","TODO");
      dfile.AddTotal(data_cubes,"data_cubes_Total","TODO");
      dfile.AddMin(data_cubes,"data_cubes_Min","TODO");
      dfile.AddMax(data_cubes,"data_cubes_Max","TODO");
      dfile.AddFun<int>(test_fun,"test_fun_Fun","TODO");
      dfile.AddVar<int>(test_int,"test_int_Var","TODO");
      dfile.AddFun<nlohmann::json>(test_json,"test_json","TODO");

      double frac = 0.0;
      for (size_t i = 0; i < 10; i++) {
          test_int += i;
          data_fracs.Add(frac += 0.01);
          data_squares.Add((int)(i*i));
          data_cubes.Add(i*i*i);
          dfile.Update();
      }
    }

    std::ifstream attempt_ifs("test_json_file.json");
    nlohmann::json attempt = nlohmann::json::parse(attempt_ifs);

    std::ifstream actual_ifs("data/test_json_file.json");
    nlohmann::json actual = nlohmann::json::parse(actual_ifs);

    REQUIRE(attempt == actual);
}

TEST_CASE("Test HtmlDataFile", "[data]") {

  // emp::HtmlDataFile needs to go out of scope
  // in order to have the destructor called
  // in order to have the finishing touches applied
  // for a valid JSON file
    {
      emp::HtmlDataFile dfile("test_html_file.html");


      emp::DataMonitor<double> data_fracs;
      emp::DataMonitor<int> data_squares;
      emp::DataMonitor<uint64_t> data_cubes;

      int test_int = 5;
      auto test_fun = [](){
        static int val = 10;
        return val += 3;
      };

      dfile.AddCurrent(data_fracs,"data_fracs_Current","TODO");
      dfile.AddCurrent(data_squares,"data_squares_Current","TODO");
      dfile.AddCurrent(data_cubes,"data_cubes_Current","TODO");
      dfile.AddMean(data_cubes,"data_cubes_Mean","TODO");
      dfile.AddTotal(data_cubes,"data_cubes_Total","TODO");
      dfile.AddMin(data_cubes,"data_cubes_Min","TODO");
      dfile.AddMax(data_cubes,"data_cubes_Max","TODO");
      dfile.AddFun<int>(test_fun,"test_fun_Fun","TODO");
      dfile.AddVar<int>(test_int,"test_int_Var","TODO");
      dfile.PrintHeaderKeys();

      double frac = 0.0;
      for (size_t i = 0; i < 10; i++) {
          test_int += i;
          data_fracs.Add(frac += 0.01);
          data_squares.Add((int)(i*i));
          data_cubes.Add(i*i*i);
          dfile.Update();
      }
    }

```

**Comment by mmore500** [comment]
Excitingly, we can have functions that return `nlohmann::json` objects registered to `JsonDataFile` so users can shove arbitrary JSON objects into their output files!

**Comment by mmore500** [comment]
Would love feedback and thoughts at this point! @mercere99  @emilydolson :smiley_cat:

**Comment by emilydolson** [comment]
I think this is awesome and I'm super excited for it! The third-party library seems well tested, documented, and supported. Moreover, it seems consistent with Empirical's design philosophy (it's header only, makes good use of debug-mode, and uses the same license; I haven't looked at how much it offloads to the compiler yet).

I haven't looked at the code in depth yet. One higher-level thought: We should think a bit about how we want to organize user dependencies (as opposed to developer dependencies like doxygen). Currently, we've got the minified version of d3 and another d3-related library living in source/web/d3, the minified version of jquery living in examples/web, and now this dependancy sitting in third-party, which is otherwise only used for developer dependencies. We probably want to come up with something more systematic. In particular, I notice that the Readme for this JSON library (and a few others I encountered recently) makes reference to a number of C++ dependency management systems. We might want to investigate those; we'll probably eventually want to make Empirical available via one or more of them. This may or may not have implications for how we should organize dependencies.

**Pull request closed without merging**
