### PR TITLE
Update Catch to latest version

### PR DESCRIPTION
**Pull request by mmore500**
This should fix `auto_ptr` issues with newer version of Clang.

### CODE REVIEW

**Comment by mmore500** [comment]
Also, safety-proof Catch dependency.

**Comment by amlalejini** [comment]
This looks great to me assuming tests pass on travis! Question: will the catch2 git sub-module be tied to a specific commit tag of catch2?

**Comment by mmore500** [comment]
Yup! Catch @ 0f05c03... I think this will lead to the fewest headaches instead of tracking master.

**Comment by mmore500** [comment]
(The only reason that having a pinned commit was an issue was that Catch was using auto_ptr , which has been removed from newer versions of C++ and was causing issues with new compilers. This kind of situation doesn't seem likely to arise again soon.)

**Comment by amlalejini** [comment]
RE: pinned commit
I totally agree that pinning is the way to go!

**Comment by mmore500** [comment]
@amlalejini tests passed! ready to merge

**Pull request merged**
