### PR TITLE
Document ALL the modules!

### PR DESCRIPTION
**Pull request by bocajnotnef**
Wheeee

~~Not ready for merge yet.~~

### CODE REVIEW

**Comment by bocajnotnef** [comment]
note that this is based off of #25, so that should probably get merged first.

**Comment by bocajnotnef** [comment]
Heh. Doxygen doc'd alllll the defines

image

**Comment by bocajnotnef** [comment]
@mercere99 Ready for merge! (though please merge #25 first)

**Comment by mercere99** [comment]
Oh goodness.  Is it worth telling Doxygen to NOT doc some of the defines?

**Comment by bocajnotnef** [comment]
Probably. I don't imagine we'll need docs on virtually anything in `macro_math` which is where the vast majority of them come from, so I might just remove that file from the library documentation.

**Pull request merged**
